// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shvuppkxddimjsitnabo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNodnVwcGt4ZGRpbWpzaXRuYWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzOTAxOTMsImV4cCI6MjA1MTk2NjE5M30.8zzRDxDFYyglqZKkHiIsXzSFh6uTkpaPQ0ZBloL0pfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);